version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "live"
    ignored_updates:
      - match:
          dependency_name: "@types/node"
          version_requirement: ">=11"
    automerged_updates:
      - match:
          dependency_type: "production"
          update_type: "semver:patch"
      - match:
          dependency_type: "development"
          update_type: "semver:minor"
    default_reviewers:
      - "oBusk"
